### PR TITLE
Project setup

### PR DESCRIPTION
**Pull request by carsonwolber**
This initial PR is just setting the foundation of my project. I set up some basic routing to direct to the correct page, and set up the flask backend to connect to an empty postgres server. Beyond that, this PR includes some basic directory setup,

### CODE REVIEW

**Review by pangers — APPROVED** [review]
Seems fine, its just project setup.

As a tip, for each pull request, it might be worth adding screenshots/demo videos of the changes in the pull request. It helps us visualize what the changes look like.

Another tip is to make more frequent pull requests (and not making too many commits in one pull request). It makes it easier to review the changes as reviewers.

**Review by lamchiminhmark — APPROVED** [review]
What does vitejs do? Otherwise looks good!

**Comment by carsonwolber** [comment]
> What does vitejs do? Otherwise looks good!


vite acts kinda like liveserver in vsCode in that it offers a quick setup for local hosting (all I do is run `npm run dev` to get local hosting up). I think it also helps streamline fulling launching online but I'm not very familiar with that side of it.

**Comment by carsonwolber** [comment]
Merging setup back into main

**Comment by William-La** [comment]
Big plus one to the points James made. Smaller PRs with less commits will make code reviews and iteration much easier. Screenshots / demos will help act as test plans for these PRs, and ideally every PR has a test plan.

Exciting to see the start of the project!

**Pull request merged**
